from heap import MaxHead

my_heap = MaxHead()
my_heap.insert(34)
my_heap.insert(4)
my_heap.insert(64)
my_heap.insert(94)
my_heap.insert(53)
my_heap.insert(100)
my_heap.insert(2)
my_heap.insert(3)
my_heap.insert(3)
my_heap.insert(12)
print(my_heap.heap)
my_heap.remove()
print(my_heap.heap)
my_heap.remove()
print(my_heap.heap)
my_heap._sink_down(12)
print(my_heap.heap)