from graph import Graph

my_graph = Graph()
my_graph.add_vertex('A')
my_graph.add_vertex('B')
my_graph.add_vertex('C')
my_graph.add_vertex('D')
my_graph.add_vertex('E')
my_graph.print_graph()
my_graph.add_vertex('D')
my_graph.add_vertex('F')
my_graph.print_graph()
print(my_graph.add_edge('A','B'))
my_graph.print_graph()
print(my_graph.add_edge('C','A'))
my_graph.print_graph()
print(my_graph.remove_edge('A','B'))
my_graph.print_graph()
print(my_graph.remove_edge('C','A'))
my_graph.print_graph()
print(my_graph.remove_vertex('A'))
my_graph.print_graph()
