from link_list import LinkedList

list_element = LinkedList(1)
list_element.append(2)
list_element.append(3)
list_element.append(4)
print(list_element.print_list())
print(list_element.pop())
print(list_element.pop())

list_element.prepend(0)
list_element.prepend(-1)
list_element.prepend(-2)
list_element.prepend(-3)
print(list_element.print_list())
print(f'Element poped: {list_element.pop_first()}')
print(list_element.print_list())
print(f'Element got: {list_element.get(2).value}')
list_element.set_value(2, 10)
print(list_element.print_list())
list_element.insert(3, -100)
print(list_element.print_list())
list_element.insert(0, -100)
print(list_element.print_list())
list_element.insert(list_element.length, -100)
print(list_element.print_list())
list_element.remove(list_element.length - 1)
print(list_element.print_list())
list_element.remove(0)
print(list_element.print_list())
list_element.remove(2)
print(list_element.print_list())
list_element.reverse()
print(list_element.print_list())


